
### Register User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "name": "Ajay Kumar",
  "email": "ajpostbox13@gmail.com",
  "password": "ajay@123"
}

###

### Login User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "ajpostbox13@gmail.com",
  "password": "ajay@123"
}

###

### Add Task 1: Buy groceries
POST http://localhost:5000/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGJlMjZiMWRhOTEyZjExZWM3YzY5ZCIsImlhdCI6MTczNzIyMTI1MSwiZXhwIjoxNzM5ODEzMjUxfQ.nQm7u3kKT5fD2XaAMEv7MuQ5LuwUCmvyJXJLDglI2hQ

{
  "name": "Buy groceries",
  "isCompleted": false
}


###

### Add Task 2: Complete project work
POST http://localhost:5000/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGJlMjZiMWRhOTEyZjExZWM3YzY5ZCIsImlhdCI6MTczNzIyMTI1MSwiZXhwIjoxNzM5ODEzMjUxfQ.nQm7u3kKT5fD2XaAMEv7MuQ5LuwUCmvyJXJLDglI2hQ

{
  "name": "Optimize Code for Performance",
  "completed": false
}

GET https://node-js-task-manager-ajays-projects-a8515549.vercel.app/



















### Get All Tasks
GET http://localhost:5000/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OGJlMjZiMWRhOTEyZjExZWM3YzY5ZCIsImlhdCI6MTczNzIyMTI1MSwiZXhwIjoxNzM5ODEzMjUxfQ.nQm7u3kKT5fD2XaAMEv7MuQ5LuwUCmvyJXJLDglI2hQ



### Create a New Task




### Task 1: Learn Node.js


### Task 2: Learn Express.js

### Task 3: Build a Task Manager App


### Task 4: Write Unit Tests for Backend


### Task 5: Learn MongoDB


### Task 6: Implement Authentication


### Task 7: Debug the Application


### Task 8: Write API Documentation


### Task 9: Deploy the Application
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "name": "Deploy the Application",
  "completed": false
}

### Task 10: Optimize Code for Performance
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "name": "Optimize Code for Performance",
  "completed": false
}
